package Nag.HibernateMappings.HibernateMappings;

public class CSVHeaderConstant {

	
	public static final String EXCEPTION_REPORT = "REF_ID,APPLICANT_NAME,CREATED_DATE,LOAN_AMOUNT,SANCTION_LOAN_AMOUNT,BRANCH_NAME,CURRENT_STAGE_ID,"+
            "OPERATOR,NUCLEUS_ID,BM_RECOMMENDED_AMT,STAGE_IN_DATE_LEAD,STAGE_OUT_DATE_LEAD,STAGE_IN_DATE_BI,"+
            "STAGE_OUT_DATE_BI,STAGE_IN_DATE_CI,STAGE_OUT_DATE_CI,STAGE_IN_DATE_CP,STAGE_OUT_DATE_CP,STAGE_IN_DATE_CA,"+
            "STAGE_OUT_DATE_CA,STAGE_IN_DATE_LA,STAGE_OUT_DATE_LA,STAGE_IN_DATE_MOD,STAGE_OUT_DATE_MOD,STAGE_IN_DATE_PREDISB,"+
            "STAGE_OUT_DATE_PREDISB,STAGE_IN_DATE_DISB,LAST_COMPLETE_STAGE,LAST_COMPLETE_USERID,REJECTION_REASON,PENDING_REASON,"+
            "TENURE,EMI,ROI,SOURCING_USERID,BM_USERID,FC_USERID,PC_USERID,AC_USERID,AL_USERID,MOD_USERID,PRE_DISB_USERID,ZONE";
}
